### PR TITLE
create all containers components to results flow

### PR DESCRIPTION
**Pull request by javierlopezdeancos**
resolve issues
#23
#24
#25
#26
#27
#28

and 
#21

in order to run this new functionalities you should remove node_modules

`rm -r node_modules`

and install again

`npm i`

### CODE REVIEW

**Comment by mdelapenya** [comment]
It would be great having commits identifying issues. Do you think it's possible?

**Comment by javierlopezdeancos** [comment]
I commit all this things in train this afternoon and I can't have connection internet to view issues numbers 💩.

Is possible change commits messages in easy way right now?

**Comment by javierlopezdeancos** [comment]
when you can see this convention is added to our wiki https://github.com/craftsmanship-toledo/katangapp-frontend/wiki/Formato-de-commits

**Comment by mdelapenya** [comment]
Sure, that convention is awesome! I meant adding issue Id (#id) after icon

**Pull request merged**
