### PR TITLE
🤖 update backend endpoint

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by javierlopezdeancos** [comment]
Looks good to me 

image

maybe I wait to merge [#22](https://github.com/craftsmanship-toledo/katangapp-frontend/pull/22) first

**Comment by mdelapenya** [comment]
It's written just on top of #22, so you could close that and keep this

**Comment by javierlopezdeancos** [comment]
ok I close the [#22](https://github.com/craftsmanship-toledo/katangapp-frontend/pull/22) and review this

**Comment by mdelapenya** [comment]
Awesome!

image

**Pull request merged**
